name: Render video
on:
  workflow_dispatch:
    inputs:
      title:
        description: "What should the title be?"
        required: true
        default: "Hello, world!"
      level:
        description: "What should the level be?"
        required: true
        default: "Level A1"
      content:
        description: "What should the content be?"
        required: true
        default: "Life is not always easy. There will be times when no one is there to guide you. No one will push you to wake up early. No one will remind you to chase your dreams. You must be the one to take action. You must learn to rely on yourself. Because if you wait for others, you will wait forever. People have their own struggles, their own lives. They may love you, but they cannot live for you. You must be strong enough to face challenges alone"

jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: oven-sh/setup-bun@v2
      - run: bun i
      - run: echo $WORKFLOW_INPUT > input-props.json
        env:
          WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}
      - run: bunx remotion render TikTok out/video.mp4 --props="./input-props.json"
      - run: node upload.js
        env:
          UPLOADTHING: ${{ secrets.UPLOADTHING }}
